[project]
# Whether to enable telemetry (default: true). No personal data is collected.
enable_telemetry = true

# List of environment variables to be provided by each user to use the app.
user_env = []

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 3600

# Duration (in seconds) of the user session expiry
user_session_timeout = 1296000  # 15 days

# Enable third parties caching (e.g. LangChain cache)
cache = false

# Whether to persist user environment variables (API keys) to the database
persist_user_env = false

# Whether to mask user environment variables (API keys) in the UI
mask_user_env = false

# Authorized origins
allow_origins = ["*"]

[features]
# Process and display HTML in messages.
unsafe_allow_html = false

# Process and display mathematical expressions.
latex = false

# Enable rendering of user messages markdown
user_message_markdown = true

# Autoscroll new user messages at the top of the window
user_message_autoscroll = true

# Autoscroll new assistant messages
assistant_message_autoscroll = true

# Automatically tag threads with the current chat profile
auto_tag_thread = true

# Allow users to edit their own messages
edit_message = true

# Allow users to share threads
allow_thread_sharing = false

# Enable favorite messages
favorites = false

[features.slack]
reaction_on_message_received = false

[features.spontaneous_file_upload]
enabled = true
accept = ["*/*"]
max_files = 20
max_size_mb = 500

[features.audio]
enabled = false
sample_rate = 24000

[features.mcp]
enabled = false

[features.mcp.sse]
enabled = true

[features.mcp.streamable-http]
enabled = true

[features.mcp.stdio]
enabled = true
allowed_executables = ["npx", "uvx"]

[UI]
# Name of the assistant.
name = "HR Assistant Aulab"

default_theme = "light"

# Permette di definire il logo per il tema chiaro e scuro.
# Assicurati che le immagini siano salvate nella cartella .chainlit/public/
logo_light = "public/logo_light.png"
logo_dark = "public/logo_dark.png"

# layout = "wide"

# Description of the assistant.
# description = ""

# Chain of Thought display mode.
cot = "full"

# Specify a CSS file used to customize the interface.
custom_css = "/public/app.css"

# Specify a JavaScript file.
# custom_js = "/public/test.js"

# The style of alert boxes.
alert_style = "classic"

# Confirm before starting a new chat.
confirm_new_chat = true

# Specify a custom meta image URL.
# custom_meta_image_url = ""

# Specify a custom build directory.
# custom_build = "./public/build"

[meta]
generated_by = "2.11.1"